version: "3"

services:
  postgresql:
    image: bettwanze/postgis:11-2.5.1
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql

  chirpstack-network-server:
    image: bettwanze/chirpstack-network-server:3.12.2
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - redis

  chirpstack-application-server:
    image: bettwanze/chirpstack-application-server:3.14.0
    ports:
      - 8000:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - postgresql

  chirpstack-gateway-bridge:
    image: bettwanze/chirpstack-gateway-bridge:3.10.0
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  frost:
    image: bettwanze/frost-server-http:1.14.0
    environment:
      - serviceRootUrl=http://192.168.1.1:8080/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - bus_busImplementationClass=de.fraunhofer.iosb.ilt.sta.messagebus.InternalMessageBus
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://postgresql:5432/sensorthings
      - persistence_db_username=frost
      - persistence_db_password=frost
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - nodereddata:/data

volumes:
  postgresqldata:
  nodereddata:
  redisdata:
